### ISSUE TITLE
observations(env)

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/CommonRLInterface.jl#10]
Should we add `observations(env)` as an optional interface function to return the observation space?

**Comment by mkschleg** [comment]
With this do we want to provide an abstract type for observation spaces? Or just leave that up to the environment designers?

Having a standard observation space with an interface could make defining models for agents easier. But another potential design is to just dispatch on the env when specifying the agent's internals.

**Comment by zsunberg** [comment]
Started #15 for discussion of spaces.

> But another potential design is to just dispatch on the env when specifying the agent's internals.

Can you elaborate on this? (possibly in #15)

**Comment by mkschleg** [comment]
Thanks! Didn't see this!

**Comment by zsunberg** [comment]
@mkschleg I made it after your post, so you couldn't have seen it :)
