### ISSUE TITLE
Two-layer interface

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/CommonRLInterface.jl#14]
(Note: I am not sure if this is the right idea for this julia package, but I think it is worth at least thinking about).

Some RL interfaces seem to separate the functions the environment-writer implements from the functions an algorithm-writer calls, e.g. the environment writer implements
```julia
env_step!(env, a)
```
but algorithms call
```julia
step!(env, a)
```
which, in turn, calls `env_step!`

I am not 100% sure of all the reasons for this, but I think it gives the framework-writers an extra layer to insert some helpful functionality. Can anyone think of any useful things that could be put here?

@mkschleg, in [another thread](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/68), said that "MinimalRLCore separates what is called and what is implemented by users" and "The focus of MinimalRLCore was also to create an API which lets people do what they need to for research, even if I didn't imagine it initially." Can you comment on the advantages of the separation and whether it contributes to the goal of letting people do what was not initially imagined? (also, more broadly, we'd love to hear if there are any lessons you learned in MinimalRLCore that might be useful for this package).

**Comment by mkschleg** [comment]
Right. So what makes MinimalRLCore a bit more flexible is the variable args in the main interface. This lets you define things to pass in yourself and not have issues with multiple dispatch. I quite like this when working with non-global RNGs or when I have to restart the env to a specific state.

I'm not sure the two-layer interface is necessary though. This was primarily a way for me to try to enforce a standard return structure (i.e. get_state, get_reward, is_terminal, ...). But I think if this is well documented we can implicitly enforce this.
