### ISSUE TITLE
valid_actions_mask(env)

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaReinforcementLearning/CommonRLInterface.jl#19]
Related to https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/8.

I suggest adding a `valid_actions_mask(env) :: BitVector` function that respects the following invariant:

```julia
valid_actions(env) = actions(env)[valid_actions_mask(env)]
```

I have found that when dealing with ML policies, this is often the most convenient way to access the set of valid actions.

For example, if `network` is a policy network that ends up with a softmax output and we want to pick an action based on the current state of the environment:

```julia
pi = network(get_state(env))
pi[.~valid_actions_mask(env)] = 0
pi ./= sum(pi)
action = actions(env)[rand(Categorical(pi))]
```

I do not see an easy and efficient way to emulate this pattern with only `actions` and `valid_actions`.

**Open question:** should we require that `valid_actions_mask` return a `BitVector` or should we allow anything that can be used to index an array (including a `Vector{Int}` enumerating the indices of valid actions)?

**Comment by findmyway** [comment]
> Open question: should we require that valid_actions_mask return a BitVector or should we allow anything that can be used to index an array (including a Vector{Int} enumerating the indices of valid actions)?

If we choose the name `valid_actions_mask`, then a `BitVector` would be better. Otherwise, we can use `valid_actions_indices` instead.

I think there's no need to restrict the return type to `BitVector`, sometimes a view will be returned. In some CxxWrap based environment wrappers, a `StdVector` may be returned.

**Comment by zsunberg** [comment]
For the name, please indicate your preference:
- :rocket: = `valid_actions_mask`
- :heart: = `valid_action_mask` (it seems to me that the singular version fits better - we say "bitmask" instead of "bitsmask")
- :tada: = `action_mask`

**Comment by zsunberg** [comment]
I think `mask` would be better than `indices`. It is not clear to me how you would negate a list of indices. We should require the returned value to be an `AbstractVector{Bool}`. This would include `BitVector`, static arrays, or sparse arrays for example.
