### ISSUE TITLE
clone

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/CommonRLInterface.jl#2]
I think it would be a good idea for each optional interface function to have an associated issue. I already put `clone` in the package, but I am definitely open to discussing it.

`clone(env)` will create a copy of the environment *at the current state*. A clone is assumed to be completely independent from the original environment from that point on.

Does anyone think it is a bad idea to add this as an optional interface function?

**Comment by darsnack** [comment]
Would this be substantially different from `deepcopy`?

**Comment by zsunberg** [comment]
The default `deepcopy` can be very slow (I think by default it constructs some dicts to deal with circular references), and in many cases there will be a faster way, for example if there is a reference to some large piece of data that defines the dynamics, we might want to avoid copying that. Moreover, if there is a connection to an external simulator, deepcopy might not be appropriate. In summary, `clone` might not always mean `deepcopy`, so there should be a new function.
