### ISSUE TITLE
Functions that depend on the environment state vs functions of the environment itself

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaReinforcementLearning/CommonRLInterface.jl#25]
I think there is an important distinction to be made between functions that depend on the environment's current state (`valid_actions`, `get_state`, `step!`) and functions that only depend on the environment itself (`actions`, `num_players`).

The current API does not make this distinction and I think it is worth debating whether or not this is a good thing.

In AlphaZero.jl, I make this distinction by dispatching either on `AbstractGame` or on `Type{<:AbstractGame}`. Therefore, one would have to write `available_actions(env)` but `num_actions(typeof(env))`.

* One advantage of this approach is that it allows calling functions such as `num_actions` without initializing a new environment. It also makes it clearer what functions depend on the environment's current state and what functions do not.
* A particularly interesting case is the one of the proposed `setstate!(env, state)` function (see https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/9). I feel a bit uneasy about it because conceptually speaking, the real operation we often want is to initialize a new simulation from a given state. In many cases, the thing we want to write is `env = Env(state)` or `from_state(Env, state)` and not `env = Env(); setstate!(env, state)`.

Now, there are also drawbacks on dispatching on the environment's type:

* Some information about the environment may not be present in its type. For example, an environment may be partially specified by some arguments given to its constructor. There would be a workaround here, which is to encode these arguments in the environment's type using `Val` but I am not sure this is desirable in general.
* In the specific case of `setstate!(env, state)` vs `Env(state)`, there is potentially an argument for the former, which is that it may be faster sometimes to just overwrite the state of an existing simulation session rather than creating a new simulation from scratch.

Any thoughts on this?

**Comment by findmyway** [comment]
> One advantage of this approach is that it allows calling functions such as num_actions without initializing a new environment. 

I think usually it's not a big problem to get those static information by initializing a new environment. (I mean usually they are only used once and then discarded, like initializing the size of network. Correct me if I'm wrong here.).

So from the API level, we can just assume they are all applied to environment instances. And when implementing, it can be applied to environment type for efficiency.

> In many cases, the thing we want to write is env = Env(state) or from_state(Env, state) and not env = Env(); setstate!(env, state).

I have no preference between `setstate!(env, state)` or `Env(state)`. Others may share different opinions here.

**Comment by zsunberg** [comment]
I think the downsides of having `actions(::Type{MyEnv})` that you mention far outweigh the upsides. In particular, there could be information in the environment that determines the action space that is neither a type parameter or a state parameter. I do not think that there is a fundamental performance benefit, since `actions(::MyEnv) = (-1, 0, 1)` will be recognized by the compiler as a constant.

> One advantage of this approach is that it allows calling functions such as num_actions without initializing a new environment.

Can you give a concrete example of this? My experience tells me that it can usually be avoided, and avoiding it is usually better (I noticed that you were doing it in AlphaZero, and I think avoiding it will result in a better problem-writer experience :smile:)

I think having an algorithm call `Env(state)` is problematic - it means that all information about the problem MUST be encoded in either the type or the state. Sometimes this is very unnatural.

We may want to more formally define what we mean by state.

**Comment by jonathan-laurent** [comment]
> I think usually it's not a big problem to get those static information by initializing a new environment. (I mean usually they are only used once and then discarded, like initializing the size of network. Correct me if I'm wrong here.)

Several remarks:

- I think it can be problematic to initialize a new environment just to get some static info about it. In some cases, initializing a new environment may imply spawning an external program with a high startup cost. (Note that this provides an argument for `setstate!(env, state)` versus `Env(state)`).
- Although I agree that in most cases, this static info can be computed once and stored somewhere, this is a burden that we put on the client. Right now, AlphaZero.jl contains calls to state-independent functions all over the place.
- Beyond being a consideration about efficiency, I think my point is also a consideration about clarity / elegance.

To be clear, I do not think there is a problem with the current solution and I am not trying to point out any flaw. Even to me, this debate is not clear cut and the separation I suggest might not be worth the added API complexity.

**Comment by jonathan-laurent** [comment]
@zsunberg I think you are making a fair assessment. I had anticipated the problem of encoding too much information in the environment type but you are also making an important point that we should make life easier for problem writers before we optimize the experience of algorithms writers.

In AlphaZero.jl, I am leveraging the fact that static info such as the number of actions can be obtained from the environment type to do things such as having a ResNet{Env} type that is aware of the environment it is targeting and whose constructor can therefore infer the right sizes for the input and output layers. I am starting to suspect this might be an anti-pattern though.

More generally, I still like the clarity of distinguishing between functions that depend on the environment state vs functions of the environment itself but I agree it should not be achieved at the expense of making the API less convenient for problem writers.

**Comment by zsunberg** [comment]
> More generally, I still like the clarity of distinguishing between functions that depend on the environment state vs functions of the environment itself

Yes, totally agree. `actions(env)` is like this now, and I worry that people will make it state dependent (perhaps we should rename it `all_actions`?). Currently the only way to indicate this is with documentation. If there was some symbol we could put in the name (similar to `!` for mutating functions in Julia), it would be helpful.

Perhaps we should put some standard text in the docstrings. I propose
```
This function is a static property of the environment; the value it returns should not change based on the state.
```
Does that seem good?

**Comment by jonathan-laurent** [comment]
Yes, I think that clarifying this in the documentation would be good.
This property could also be tested in an environment test suite if we provide one.
