### ISSUE TITLE
is this meant to be the "ring to rule them all"

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaReinforcementLearning/CommonRLInterface.jl#30]
If I am to implement an RL environment that plays nice with JuliaReinforcementLearning. Is this the interface to implement?

**Comment by zsunberg** [comment]
That is the eventual hope, or at least this will be a "least common denominator" where you will have basic interoperability. We haven't quite had time to make that a reality though yet :) At this moment, I am not sure if there are any solvers that will work with it yet, haha
