### ISSUE TITLE
The documentation links in the README are currently broken

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaReinforcementLearning/CommonRLInterface.jl#32]
The documentation links in the README are currently broken:
https://juliareinforcementlearning.org/CommonRLInterface.jl/stable
https://juliareinforcementlearning.org/CommonRLInterface.jl/dev

**Comment by zsunberg** [comment]
Currently the only documentation is the README - adding more documentation is a future goal (#24). I commented out the doc links for now (404e87b)
