### ISSUE TITLE
Incomplete documentation for `player(env)`

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaReinforcementLearning/CommonRLInterface.jl#34]
The documentation for `player(env)` currently says the following:

```
"""
    player(env::AbstractZeroSumEnv) 
Return the index of the player who should play next in the environment.
This is a *required function* for all `AbstractZeroSumEnvs`.
"""
```

I think we should be more specific about what player indexes can be:
- Should we have a function `all_players(env)` returning all valid indexes? Still, it does not resolve the question: what players are maximizing players and what players are minimizing players?
- Should we limit the interface to having two players? In this case, maybe having an enum defining `MaximizingPlayer` and `MinimizingPlayer` would be better.

**Comment by zsunberg** [comment]
Right now in the README and the  it says explicitly that `AbstractZeroSumEnv` is two player. I thought that we should wait until we have more experience to try to design an interface for arbitrary n-player games.

The `AbstractZeroSumEnv` does say that player 1 is maximizing and 2 is minimizing. https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/blob/404e87b08ba02a2b22add0b2c6f7965ae6e09544/src/CommonRLInterface.jl#L33 Would be good to either say this in the `player` docstring as well or link back to the `AbstractZeroSumEnv`.

We could consider making an enum or two different types, but I actually kind of think it will be simpler just to keep it as `Int`s and document it better. We may want to re-use the `player` function for n-player games and have it return an Int.

**Comment by jonathan-laurent** [comment]
I had missed this line in the documentation, thanks!

To be clear, I was not suggesting that we should add support for n-player games right now.
Even for two-player, zero-sum games, it might have made sense to allow more than two players which are split into two teams. But this does not really add any expressiveness and so arguably there is no need for it in this package.
