### ISSUE TITLE
POMDPs.jl integration

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/CommonRLInterface.jl#35]
Just wanted to leave this issue here to say that integrating this with POMDPs.jl is on my radar, I just have not had time to work on it.

**Comment by zsunberg** [comment]
If anyone else wants to, I would be happy to provide feedback and guidance.

**Comment by MaximeBouton** [comment]
I would be happy to help or at least participate in the conversation!

**Comment by zsunberg** [comment]
Started work on this in JuliaPOMDP/POMDPs.jl#325

**Comment by zsunberg** [comment]
Now working here: JuliaPOMDP/POMDPModelTools.jl#44

**Comment by zsunberg** [comment]
Finished! Closed with JuliaPOMDP/POMDPModelTools.jl#44
