### ISSUE TITLE
Clone function confusion

### ISSUE THREAD

**Issue by casper2002casper** [JuliaReinforcementLearning/CommonRLInterface.jl#48]
I'm a bit confused about the clone function. The documentation states that it should create a completely independent copy, however in the GridWorld example the following is used `@provide RL.clone(env::GridWorld) = GridWorld(env.size, copy(env.rewards), env.state)`.  What is the reason the copy function is only is used for the rewards function, wouldn't you want to create a deepcopy of the state to create independent instances instead of the rewards?

**Comment by jonathan-laurent** [comment]
The `copy` function is only used on the `rewards` field because it is the only field that contains mutable data.

**Comment by casper2002casper** [comment]
I see, thank you.
