### ISSUE TITLE
valid_actions(env)

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/CommonRLInterface.jl#8]
In e.g. MCTS it is often nice to get a list of a subset of actions that are valid in the environment. `validactions(env)` is an interface function that could provide such a list.

Should we add this as an optional interface function?

**Comment by rejuvyesh** [comment]
`validactions` would be a function of the current `state` of the `env`?

**Comment by findmyway** [comment]
1. Personally I prefer `valid_actions` instead of `validactions`, easier to read. ( [function-naming](https://github.com/invenia/BlueStyle#function-naming) )

> `validactions` would be a function of the current `state` of the `env`?

This brings in some more interesting questions:

- What is the `state` of `env`?
- Should we also have an optional interface function named `get_state`?
- Is it included in the `info` of the result from `step!`? (`obs, reward, done, info`)

**Comment by zsunberg** [comment]
> validactions would be a function of the current state of the env?

Yes

> Personally I prefer valid_actions instead of validactions, easier to read.

Ok, yeah, I did that to match the [Julia style guide](https://docs.julialang.org/en/v1/manual/style-guide/index.html#Use-naming-conventions-consistent-with-Julia-base/-1), but I like the underscore version better. Maybe we should adopt that "blue style"?

> What is the state of env?

Assuming env represents a Markov decision process, it is the markov state of that MDP. For some environments, that might be very concrete, for others it might be very hard to extract.

> Should we also have an optional interface function named get_state?

That seems reasonable. I would vote for just `state(env)`. It seems like most julia libraries don't use `get`. You should open an issue.

> Is it included in the info of the result from step!? (obs, reward, done, info)

I don't think this package should stipulate that anything be contained in info. We should add optional functions for any behavior we want to standardize.

**Comment by darsnack** [comment]
Since we've started down this path, I personally think it should be `actions(state(env))`. This is my interpretation of the "blue style" suggestions. Most of this stuff makes sense in context with other code.

But this gets 👍 for adding to the optional interface.

**Comment by darsnack** [comment]
Actually after thinking about it, shouldn’t it be `actions(env)`? I agree that the actions can depend on the state, but that should be left to the environment writer. They’ll know whether to get the current state in the implementation.

**Comment by zsunberg** [comment]
> actions(state(env))

This won't be very convenient. Consider, for instance, a gridworld where actions going off the edge are not valid. The state might be a `SVector{2, Int}`, but the size would be a static environment parameter. You need the static parts of the environment and the dynamic state to determine the valid actions.

> actions(env)

This is what I was originally thinking, but I don't think it will work. Many algorithms (especially the ones tinkerers will write) need to know the entire action space to set up correctly. We will need a way to reliably get the full space.

**Comment by darsnack** [comment]
> We will need a way to reliably get the full space.

Okay so we need `actions(env)` to return the full space, but `valid_actions(env)` to return currently allowed actions? I would prefer using a keyword arg `allowed`/`available` for this. I find that more intuitive and easier to keep track of then allowing the # of functions in the interface to increase.

**Comment by zsunberg** [comment]
> Okay so we need actions(env) to return the full space, but valid_actions(env) to return currently allowed actions?

Correct

> I would prefer using a keyword arg allowed/available for this. I find that more intuitive and easier to keep track of then allowing the # of functions in the interface to increase.

I don't see a larger number of functions as being particularly problematic - clarity should be the first priority. Hmm... this is a bigger question than just for `valid_actions`: In general, should we support optional behavior through more functions or optional keyword args? I think keyword args might make things more tricky, but I need to think about it. Could you open a new thread for this?

**Comment by zsunberg** [comment]
One trouble with keyword arguments is how `provided` would handle them. It doesn't seem too difficult to handle optional positional arguments, but Julia's `applicable` appears to not handle keyword args, so there may not be an obvious clean way.
