### ISSUE TITLE
setstate!(env, state)

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/CommonRLInterface.jl#9]
In some environments, it is possible to set the state. Should we add `setstate(env, state)` as an optional interface function?

**Comment by mkschleg** [comment]
I think this is reasonable. Another possibility is to add it as a method for `reset!`.

**Comment by zsunberg** [comment]
We'll need to decide which one. Let's vote:

:rocket: = `setstate!(env, state)`
:tada: = `reset!(env, state)`
